export const LOGIN_ERROR = 'LOGIN_ERROR';
export const SELECT_FRIEND_CHAT = 'SELECTED_FRIEND_CHATING';
export const SENDING_MESSAGE = 'SENDING_MESSAGE';
export const LOGIN = 'LOGIN_CHAT_APP';
export const LOGOUT = 'LOG_OUT_CHAT_APP';
